name: Compile Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Compile to EXE
        run: |
          pyinstaller --onefile main.py
          dir dist

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: main-exe
          path: dist/main.exe
          if-no-files-found: warn
